### ISSUE TITLE
Same vector produced for all proteins

### ISSUE THREAD

**Issue by serbulent** [hkmztrk/SMILESVecProteinRepresentation#5]
When I try to generate protein vectors with;

`python getligprotvec.py drug.l8.chembl23.canon.ws20.txt`

command, same vector is written to protein.vec file. I'm attaching prots_sample.txt and protein.vec files.

[prots_sample.txt](https://github.com/hkmztrk/SMILESVecProteinRepresentation/files/3900435/prots_sample.txt)

[protein.vec.zip](https://github.com/hkmztrk/SMILESVecProteinRepresentation/files/3900439/protein.vec.zip)

**Comment by hkmztrk** [comment]
Hello @serbulent, can you send me the prot.vec file for the ten  or so selected protein ids please?

**Comment by serbulent** [comment]
Hello,

They are already attached in the first message. If you can't download them I may share them from gDrive.

**Comment by hkmztrk** [comment]
Hello, sorry for my late reply. 
Pickle file didn't seem correct to me - it should had been something unreadable in binary form. That was what I meant when requesting first five or ten samples.

**Comment by serbulent** [comment]
Hello again,

I'm attaching files for fist 20 proteins. Although vectors are created for only 4 of them but the problem is still exits. I check the protein.vec file and ensure that it can be opened with pickle by the method we talked before as after opening the zip file;

```
with open('/protein.vec', 'rb') as f:
         SmilesVecTmp = pickle.load(f, encoding='bytes')

```
[prots_sample.txt](https://github.com/hkmztrk/SMILESVecProteinRepresentation/files/4126604/prots_sample.txt)

[protein.vec.zip](https://github.com/hkmztrk/SMILESVecProteinRepresentation/files/4126607/protein.vec.zip)

**Comment by hkmztrk** [comment]
Hello @serbulent, I updated the repo. Could you please check the new version and let me know whether it works or not?

Best.

**Comment by serbulent** [comment]
Hello,

Thanks so much it seems works now for the last test case.

Best.
